services:
  ws:
    image: ${WS_IMAGE}
    build:
      dockerfile: Dockerfile.${PROFILE}
      context: ./ws
    depends_on:
      - was
      - client
    ports:
      - ${WS_PORT}:${WS_PORT}
    environment:
      - DOMAIN=${WS_DOMAIN}
      - PORT=${WS_PORT}
      - WAS_PORT=${WAS_PORT}
      - CLIENT_PORT=${CLIENT_PORT}
    volumes:
      - ./ws:/ws
      - dist:/dist
  was:
    image: ${WAS_IMAGE}
    build:
      dockerfile: Dockerfile.${PROFILE}
      context: ./was
    ports:
      - 5050:5050
    expose:
      - ${WAS_PORT}
    environment:
      - PORT=${WAS_PORT}
      - DB_DRIVER_CLASS_NAME=${DB_DRIVER_CLASS_NAME}
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./was:/was
  client:
    image: ${CLIENT_IMAGE}
    build:
      dockerfile: Dockerfile.${PROFILE}
      context: ./client
    expose:
      - ${CLIENT_PORT}
    environment:
      - PORT=${CLIENT_PORT}
      - WS_PROTOCOL=${WS_PROTOCOL}
      - WS_DOMAIN=${WS_DOMAIN}
      - WS_PORT=${WS_PORT}
    volumes:
      - ./client:/client
      - dist:/dist

volumes:
  dist:
